version:  '3'
services:
  mesher-consumer:
    image: gochassis/mesher:1.5rc
    environment:      
      CSE_REGISTRY_ADDR: http://127.0.0.1:30100
      SERVICE_NAME: "mesher-consumer"
    network_mode: "service:node-client-example"
    depends_on:
      - node-client-example  
  node-client-example:
    build: ./node-client
    environment:
      http_proxy: http://127.0.0.1:30101
    ports:
      - 8888:80