version:  '3'
services:
  node-client:
    build: ./node-client
    environment:
      http_proxy: http://127.0.0.1:30101
    network_mode: "service:mesher-consumer"
    depends_on:
      - mesher-consumer  
  mesher-consumer:
    #image: medci-mesher
    build: ./mesher-linux
    ports:
      - 81:80
    environment:
      CSE_REGISTRY_ADDR: http://192.168.1.101:30100
      SERVICE_NAME: "mesher-consumer"

